site_name: Virtual Dressing Project
nav:
- Overview: index.md
- Catalogue: Requirement.md
- Minutes: 
  - Meeting Catelogue: MeetingCatalogue.md
  - Meeting01: Meeting01.md
  - Meeting02: Meeting02.md
  - Meeting03: Meeting03.md
  - Meeting05: Meeting05.md
  - Meeting08: Meeting08.md
  - Meeting09: Meeting09.md
  - Meeting10: Meeting10.md
  - Meeting11: Meeting11.md
  - Meeting12: Meeting12.md
  
theme: 
  name: simple-blog
  title_style: bold
