site_name: Virtual Dressing Project
nav:
- Overview: index.md
- Catalogue: Requirement.md
- Minutes: 
  - Meeting Catelogue: MeetingCatalogue.md
  - Meeting01: Meeting01.md
  - Meeting02: Meeting02.md
  - Meeting03: Meeting03.md
theme: 
  name: simple-blog
  title_style: bold
